//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagement.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Not found.
        /// </summary>
        public static string AddressNotfound {
            get {
                return ResourceManager.GetString("AddressNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Not Found.
        /// </summary>
        public static string AdminNotFound {
            get {
                return ResourceManager.GetString("AdminNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty field.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already set your account extra data.
        /// </summary>
        public static string ExtraDataAlreadyAdded {
            get {
                return ResourceManager.GetString("ExtraDataAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch user data.
        /// </summary>
        public static string FailedToFetchUserData {
            get {
                return ResourceManager.GetString("FailedToFetchUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect current password.
        /// </summary>
        public static string IncorrectCurrentPassword {
            get {
                return ResourceManager.GetString("IncorrectCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect data.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect email or password.
        /// </summary>
        public static string IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the email format is incorrect.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number format, they must be {0} in order, {1} like this.
        /// </summary>
        public static string InvalidPlaceholderFormat {
            get {
                return ResourceManager.GetString("InvalidPlaceholderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Not found.
        /// </summary>
        public static string NotAccessDeleteThisAddress {
            get {
                return ResourceManager.GetString("NotAccessDeleteThisAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Access Edit this Address.
        /// </summary>
        public static string NotAccessEditthisAddress {
            get {
                return ResourceManager.GetString("NotAccessEditthisAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Points.
        /// </summary>
        public static string NotEnoughPoints {
            get {
                return ResourceManager.GetString("NotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found Address to User.
        /// </summary>
        public static string NotFoundAddresstoUser {
            get {
                return ResourceManager.GetString("NotFoundAddresstoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Transactions Found.
        /// </summary>
        public static string NoTransactionsFound {
            get {
                return ResourceManager.GetString("NoTransactionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Wallet Found.
        /// </summary>
        public static string NoWalletFound {
            get {
                return ResourceManager.GetString("NoWalletFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this phone is already exist.
        /// </summary>
        public static string PhoneNumberAlreadyUsed {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this name is already exist.
        /// </summary>
        public static string RedundantData {
            get {
                return ResourceManager.GetString("RedundantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        public static string SuccessChangePassword {
            get {
                return ResourceManager.GetString("SuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation.
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Percentage Not Found.
        /// </summary>
        public static string SystemPercentageNotFound {
            get {
                return ResourceManager.GetString("SystemPercentageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password cannot be the same as the old password..
        /// </summary>
        public static string Thenewpasswordcannotbethesameastheoldpassword_ {
            get {
                return ResourceManager.GetString("Thenewpasswordcannotbethesameastheoldpassword.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Address Already Exciting.
        /// </summary>
        public static string ThisAddressAlreadyExciting {
            get {
                return ResourceManager.GetString("ThisAddressAlreadyExciting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this email is already exist.
        /// </summary>
        public static string thisemailisalreadyexist {
            get {
                return ResourceManager.GetString("thisemailisalreadyexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Failed.
        /// </summary>
        public static string TransactionsFailed {
            get {
                return ResourceManager.GetString("TransactionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted Successfully.
        /// </summary>
        public static string UserDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Restored Successfully.
        /// </summary>
        public static string UserRestoredSuccessfully {
            get {
                return ResourceManager.GetString("UserRestoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor details not found in vendor repository.
        /// </summary>
        public static string Vendordetailsnotfoundinvendorrepository {
            get {
                return ResourceManager.GetString("Vendordetailsnotfoundinvendorrepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Cannot Modify Another User Is Account.
        /// </summary>
        public static string YouCannotModifyAnotherUserIsAccount {
            get {
                return ResourceManager.GetString("YouCannotModifyAnotherUserIsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Cannot Modify Another User Is Account. Please Edit Your Own Account Only.
        /// </summary>
        public static string YouCannotModifyAnotherUserIsAccount_PleaseEditYourOwnAccountOnly {
            get {
                return ResourceManager.GetString("YouCannotModifyAnotherUserIsAccount.PleaseEditYourOwnAccountOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account has been blocked.
        /// </summary>
        public static string YourAccountHasBeenBlocked {
            get {
                return ResourceManager.GetString("YourAccountHasBeenBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account has been deactivated.
        /// </summary>
        public static string YourAccountHasBeenDeactivated {
            get {
                return ResourceManager.GetString("YourAccountHasBeenDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account has been locked out.
        /// </summary>
        public static string YourAccountHasBeenLockedOut {
            get {
                return ResourceManager.GetString("YourAccountHasBeenLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your email has not been confirmed yet.
        /// </summary>
        public static string YourEmailNotConfirmedYet {
            get {
                return ResourceManager.GetString("YourEmailNotConfirmedYet", resourceCulture);
            }
        }
    }
}
